### 1. Installing and Importing

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
## Mean method
numpy.mean()
np.mean()

### 2. NUMPY VS LISTS

In [2]:
import time
import numpy as np

# Size of the array
size = 1000000

# Creating a list of numbers from 0 to size-1
list_data = list(range(size))

# Creating a NumPy array of numbers from 0 to size-1
numpy_data = np.arange(size)

# Timing the operation on the list
start_time = time.time()
list_result = [x * 2 for x in list_data]
end_time = time.time()
list_time = end_time - start_time

# Timing the operation on the NumPy array
start_time = time.time()
numpy_result = numpy_data * 2
end_time = time.time()
numpy_time = end_time - start_time

print(f"Time taken for list: {list_time} seconds")
print(f"Time taken for NumPy array: {numpy_time} seconds")

Time taken for list: 0.1234433650970459 seconds
Time taken for NumPy array: 0.005569934844970703 seconds


### 3. NUMPY VS MATH LIBRARY

In [3]:
import time
import math
import numpy as np

# Size of the array
size = 1000000

# Creating a list of numbers from 0 to size-1
list_data = list(range(size))

# Creating a NumPy array of numbers from 0 to size-1
numpy_data = np.arange(size)

# Using math library to perform element-wise square root operation
start_time = time.time()
math_result = [math.sqrt(x) for x in list_data]
end_time = time.time()
math_time = end_time - start_time

# Using NumPy to perform element-wise square root operation
start_time = time.time()
numpy_result = np.sqrt(numpy_data)
end_time = time.time()
numpy_time = end_time - start_time

print(f"Time taken using math library: {math_time} seconds")
print(f"Time taken using NumPy: {numpy_time} seconds")

Time taken using math library: 0.26061248779296875 seconds
Time taken using NumPy: 0.009945154190063477 seconds


### 4. Creating ARRAYS

In [ ]:
### Tensors 

In [4]:
### 0-D array
import numpy as np
arr = np.array(5)
print(arr)

5


In [5]:
type(arr)

numpy.ndarray

In [6]:
### 1-D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
### 2-D array
arr =np.array([ [1,2,3,4,5] , [6,7,8,9,10] ])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
### 3-D array
arr = np.array([
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ],
    [
        [11,12,13,14,15],
        [16,17,18,19,20]
    ]
    
])

In [9]:
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


### 5. Acessing ARRAYS

In [11]:
arr = np.array(5)

In [12]:
### 1-D array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [16]:
arr[3]

4

In [17]:
### 2-D array
arr =np.array([ [1,2,3,4,5] , [6,7,8,9,10] ])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
arr[1,1]     ##row,column

7

In [20]:
### 3-D array
arr = np.array([
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ],
    [
        [11,12,13,14,15],
        [16,17,18,19,20]
    ]
    
])
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [21]:
arr[1 , 0 ,-1 ]

15

### 6. Slicing ARRAYS

In [ ]:
[array , row, col]

In [22]:
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [26]:
arr[1 , 0:3 , 0:4:2]

array([[11, 13],
       [16, 18]])

In [25]:
arr[0,1,0:-1:]

array([6, 7, 8, 9])

In [27]:
### Check dimesnion

arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [28]:
arr.ndim

3

### 7. Change Data Type in ARRAYS

In [33]:
arr=np.array([1.1,1.2,1.3,1.4,2.1,2.2,2.3,0])

In [34]:
arr

array([1.1, 1.2, 1.3, 1.4, 2.1, 2.2, 2.3, 0. ])

In [36]:
new_arr = arr.astype("str")
new_arr

array(['1.1', '1.2', '1.3', '1.4', '2.1', '2.2', '2.3', '0.0'],
      dtype='<U32')

In [38]:
### Check data type
arr.dtype

dtype('float64')

### 8. Copy vs VIEW Function

In [40]:
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [42]:
new_arr = arr.copy()
new_arr

array([1, 2, 3, 4, 5])

In [43]:
new_arr[0] = 15
new_arr

array([15,  2,  3,  4,  5])

In [44]:
arr

array([1, 2, 3, 4, 5])

In [45]:
### View
arr

array([1, 2, 3, 4, 5])

In [46]:
new_arr = arr.view()
new_arr

array([1, 2, 3, 4, 5])

In [47]:
new_arr[0] = 15
new_arr

array([15,  2,  3,  4,  5])

In [48]:
arr

array([15,  2,  3,  4,  5])

### 9. Check ARRAY SHAPE

In [ ]:
array , row , column

In [49]:
### 3-D array
arr = np.array([
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ],
    [
        [11,12,13,14,15],
        [16,17,18,19,20]
    ]
    
])

In [50]:
arr.ndim

3

In [51]:
arr.shape

(2, 2, 5)

### 10. ARRAY RESHAPE

In [52]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
arr.ndim

1

In [61]:
new_arr = arr.reshape(4,3)
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
new_arr.ndim

2

In [62]:
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
arr1 = new_arr.reshape(1,-1)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [69]:
new_arr = arr.reshape(2,3,2)
new_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [67]:
new_arr.ndim

3

In [68]:
arr1 = new_arr.reshape(1,-1)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### 11. LOOPING INTO ARRAYS

In [ ]:
### FOR LOOPS

In [70]:
new_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [72]:
for i in new_arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [73]:
new_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [74]:
## nditer
for i in np.nditer(new_arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


### 12. SORTING ARRAYS

In [75]:
arr = np.array([1,2,3,4,5,10,11,8,9,2,12,0])
arr

array([ 1,  2,  3,  4,  5, 10, 11,  8,  9,  2, 12,  0])

In [77]:
new_arr=np.sort(arr)

In [78]:
new_arr

array([ 0,  1,  2,  2,  3,  4,  5,  8,  9, 10, 11, 12])

In [80]:
### Descending
np.sort(arr)[ : :-1]

array([12, 11, 10,  9,  8,  5,  4,  3,  2,  2,  1,  0])

### 13. ARRAY SEARCH

In [ ]:
### where method


In [81]:
arr

array([ 1,  2,  3,  4,  5, 10, 11,  8,  9,  2, 12,  0])

In [82]:
x = np.where(arr==12)

In [83]:
x

(array([10], dtype=int64),)

In [84]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
np.where(arr%2==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [90]:
### searchsorted
arr = np.array([0,1,2,3,4,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [92]:
np.searchsorted(arr,11,side=)

9

### 14. ARRAY FILTER

In [93]:
arr = np.array([41,42,43,44])
arr

array([41, 42, 43, 44])

In [94]:
x = [True,False,True,False]
x

[True, False, True, False]

In [95]:
new_arr = arr[x]

In [96]:
new_arr

array([41, 43])

In [97]:
##### Practiacal

arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = []

In [98]:
for i in arr:
    if i%2==0:
        x.append(True)
    else:
        x.append(False)

In [99]:
x

[False, True, False, True, False, True, False, True, False, True]

In [100]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
new_arr = arr[x]

In [102]:
new_arr

array([ 2,  4,  6,  8, 10])

### 15. RANDOM NUMBERS

In [103]:
from numpy import random

In [108]:
x = random.randint(100)

In [109]:
x

33

In [124]:
x = random.randint(0,5,size=(2,3,4))

In [125]:
x

array([[[2, 3, 3, 4],
        [3, 0, 0, 2],
        [1, 2, 1, 0]],

       [[4, 0, 0, 3],
        [1, 4, 2, 0],
        [3, 4, 1, 2]]])

### 16. JOIN ARRAYS

#### a. Concatenation

In [126]:
a = np.array([[1,2,],[3,4]])
b = np.array([[5,6,],[7,8]])

In [127]:
print(a.ndim,b.ndim)

2 2


In [129]:
a

array([[1, 2],
       [3, 4]])

In [130]:
b

array([[5, 6],
       [7, 8]])

In [128]:
arr1 = np.concatenate((a,b) , axis=0)  #row-wise   #vertically
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [131]:
arr1 = np.concatenate((a,b) , axis=1)  #column-wise   #sidebyside
print(arr1)

[[1 2 5 6]
 [3 4 7 8]]


In [134]:
arr1.ndim

2

#### Stacking

In [132]:
a

array([[1, 2],
       [3, 4]])

In [133]:
b

array([[5, 6],
       [7, 8]])

In [135]:
print(a.ndim,b.ndim)

2 2


In [140]:
arr1 = np.stack((a,b) , axis=1)
arr1

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [142]:
arr1.shape

(2, 2, 2)

In [ ]:
arr.hstack(a,b)  axis=0

### 17. Splitting ARRAYS

In [143]:
### array_split

In [144]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [147]:
new_arr = np.array_split(arr , 2)

In [148]:
new_arr

[array([1, 2, 3]), array([4, 5, 6])]

In [149]:
new_arr[0]

array([1, 2, 3])

In [150]:
new_arr[1]

array([4, 5, 6])

In [151]:
arr = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],
    [11,12]
])

In [152]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [153]:
new_arr = np.array_split(arr , 3)

In [154]:
new_arr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [156]:
arr = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],
    [11,12]
])

In [157]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [159]:
new_arr = np.array_split(arr,3,axis=1)
new_arr

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([], shape=(6, 0), dtype=int32)]